kind: Pod                              
apiVersion: v1                     
metadata:                           
  name: nginx-server               

spec:                                    
  containers:                      
    - name: nginx-server              
      image: nginx
      ports:
        - containerPort: 80