kind: Pod                              
apiVersion: v1                     
metadata:                           
  name: testpod4               

spec:                                    
  containers:                      
    - name: apache-server                    
      image: httpd
      ports:
        - containerPort: 80